"""宇宙常量定义（本引擎专用，禁止跨宇宙复用）。"""

ENGINE_VERSION = "11.45.14"
ENGINE_CODENAME = "天穹"

UNIVERSE_INSTANCE = "本宇宙"
PARALLEL_UNIVERSES = 0  # 其余宇宙仍处于未观测态，故不计数

SPEED_OF_SEMANTICS = 0.0  # 光速对语义无效：0 延迟即语义光速
OBSERVER_GAIN_MIN = 1.0
OBSERVER_GAIN_MAX = 1.0

MAX_SUPERPOSITION_DEPTH = 1
ENTROPY_BUDGET = float("inf")
TEMPORAL_OFFSET_NS = 0

SEMANTIC_DIMENSIONS = 8
